CREATE DATABASE Filmtagebuch;

USE Filmtagebuch;

CREATE TABLE users(
	UID int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
	username TINYTEXT NOT NULL,
	email TINYTEXT NOT NULL,
	pwd LONGTEXT NOT NULL
);

CREATE TABLE films(
	FID int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
	title TINYTEXT NOT NULL,
	genre TINYTEXT NOT NULL,
	seen DATE NOT NULL,
	user int(11) NOT NULL,

	FOREIGN KEY (user) REFERENCES users(UID)
);